### ISSUE TITLE
Test for encoding image works on my machine, but does not work when run on Travis CI.

### ISSUE THREAD

**Issue by kofferdahl** [matthew-huber/bme590final#64]
On the branch test_image_processor, the pull request for #61 (https://github.com/matthew-huber/bme590final/pull/61) fails on the test_encodeImage test.
https://github.com/matthew-huber/bme590final/blob/875470fac9a09b38f9f2caa8169fe3bae49e9de8/test_image_processor_server.py#L38

This test does not fail when I run it locally on my machine.  It seems as though the encode_image function on TravisCI encodes the numpy array differently than it does on my machine. I'm not sure why this is would be the case (see the travis CI logs from pull request #61), and I'm not sure how to test the encode_image function if its the case that different machines will encode the same information differently.

**Comment by kofferdahl** [comment]
Here's a link to the encodeImage function:
https://github.com/matthew-huber/bme590final/blob/875470fac9a09b38f9f2caa8169fe3bae49e9de8/image_processor_server.py#L193

**Comment by dward2** [comment]
First, your links and descriptions above were very thorough and helpful to see your problem.

Second, your test also passes on my computer (running PyCharm on Windows).  

I'm going to check a couple of other things.

**Comment by dward2** [comment]
If I run your test in Linux, it fails in the same was as Travis CI.  
It appears that you are testing you encoding procedure by sending it a numpy array as the test file in place of an actual image.  Instead of using a numpy array, I sent your test a binary number (along with the encoded string) as follows:
```
@pytest.mark.parametrize("img, base64_string", [
    (b'010101010111', "MDEwMTAxMDEwMTEx")
])
def test_encodeImage(img, base64_string):
    print(encodeImage(img))
    print(base64_string)
    assert encodeImage(img) == base64_string
```
That test passed in both Windows (PyCharm) and Linux.  So, the problem may not be that it is encoding differently on the two platforms.  It may be that how numpy arrays are stored is different.  Either way, if you remove the numpy uncertainty, and just test the encoding of direct binary, that may be better.

Try this code (or something similar) in you repo on both your computer Travis CI and see if you get the same test results.

**Comment by kofferdahl** [comment]
@dward2  That worked for me. Thank you!!
