### ISSUE TITLE
Current master branch gives GUI error when trying to process image

### ISSUE THREAD

**Issue by matthew-huber** [matthew-huber/bme590final#66]
I've been trying to test some things out, but whenever I try to process an image, I get an error like the following that I can't figure out:
OSError: cannot identify image file <_io.BytesIO object at 0x0000026C4DD8CA98>
.
This is for the current master branch, and it is a GUI error because I've been able to have images upload successfully. The error is raised on the following line:
https://github.com/matthew-huber/bme590final/blob/22433028c30f67fd0c557bb8183985100ab54fe5/image_processor_gui.py#L337

If either of your are able to look at it, that'd be great!

**Comment by kofferdahl** [comment]
From what I can tell, it looks like there's just placeholders for the return data for now, rather than  encoded base64 strings.
https://github.com/matthew-huber/bme590final/blob/22433028c30f67fd0c557bb8183985100ab54fe5/image_processor_server.py#L14

Here's a  temporary workaround I made that just puts the original image into the place where the processed image is going to go:

After line 290 (https://github.com/matthew-huber/bme590final/blob/22433028c30f67fd0c557bb8183985100ab54fe5/image_processor_gui.py#L290) in image_processor_gui, insert the following two lines:

`         OG_img = content.get("OG Images")
        self.insert_processed_image(OG_img)`
replacing what was originally in self-insert_processed_image(OG_img).

This should work okay temporarily, as long as you don't care about testing the actual image processing functions with the GUI.

**Comment by matthew-huber** [comment]
Looks like a good fix for now- thanks

**Comment by mjp59** [comment]
@matthew-huber @kofferdahl  I should have reopened the issue when I merged on Saturday. Currently, all the image information is being transferred back to the gui correctly. However, for some reason the imread command is not recognizing the location of the buffer with the image file in the local computer's ram. I am not exactly sure why this is happening.

**Comment by mjp59** [comment]
https://github.com/matthew-huber/bme590final/blob/9b40566d5f3eed87ca1e8b5a1bf435098cc29e0a/image_processor_gui.py#L311

https://github.com/matthew-huber/bme590final/blob/9b40566d5f3eed87ca1e8b5a1bf435098cc29e0a/image_processor_gui.py#L412-L416

The following code snippets is creating a error: OSError: cannot identify image file <_io.BytesIO object at 0x0000026C4DD8CA98>.

@mlp6 @suyashkumar I am not sure why the imread command can not locate the buffer with the base 64 decoded processed image. I can't seem to find any solutions by googling. Are there any insights to why the buffer can not be identified by imread?

**Comment by mlp6** [comment]
I would run the interactive debugger with a breakpoint at that line and inspect the variable workspace to make sure that everything is in memory and of the type that you are expecting.  Do you have a unit test written that replicates this error?
