### ISSUE TITLE
gui crashes when an image is clicked in the manage file tab 

### ISSUE THREAD

**Issue by mjp59** [matthew-huber/bme590final#74]
When I go to get metadata on an image that was previously processed, the gui crashes with this error: 
File "image_processor_gui.py", line 206, in load_image_data
    self.image_pixels.setText(str(image_metadata["image_pixels"]))
KeyError: 'image_pixels'

**Comment by matthew-huber** [comment]
This error exists because of the change I made to the unique identifier in the database. I didn't clear all of the old files from the database, so when it tried to read from them it would get messed up by the lack of the username on the end of the file. I removed the troublesome filed from the database, so everything should work  for any files updated from now on. If you see the issue again, let me know
